"""Person and ParentChildRelationshop Models added

Revision ID: 0e3d69285df8
Revises: 39b2019c3c86
Create Date: 2018-11-25 12:21:16.929934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e3d69285df8'
down_revision = '39b2019c3c86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=140), nullable=True),
    sa.Column('dob', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parent_child_relationship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent', sa.Integer(), nullable=True),
    sa.Column('child', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['child'], ['person.id'], ),
    sa.ForeignKeyConstraint(['parent'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parent_child_relationship')
    op.drop_table('person')
    # ### end Alembic commands ###
